### ISSUE TITLE
实时告警报错

### ISSUE THREAD

**Issue by hanguanglinyun** [aide-family/moon#141]
### What happened?

点击页面上实时告警会报错
<img width="708" alt="企业微信截图_20240704221601" src="https://github.com/aide-family/moon/assets/48739305/f2863dcb-6215-4450-afe1-43760e34bfdb">

### What did you expect to happen?

需要修改什么配置才能修复呢?

### How can we reproduce it (as minimally and precisely as possible)?

点击页面实时告警

### moon version

v0.0.24

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

**Comment by aide-cloud** [comment]
观察中， 没复现出来， 但是好多用户提到了这个问题

**Comment by aide-cloud** [comment]
已修复，修复代码见 [PR](https://github.com/aide-family/moon/pull/142)， 感谢持续关注moon 🚀
