### ISSUE TITLE
添加prometheus数据源后再编辑告警策略无法读取指标

### ISSUE THREAD

**Issue by hanguanglinyun** [aide-family/moon#144]
### What happened?

![image](https://github.com/aide-family/moon/assets/48739305/8b5ec423-36e6-432c-9253-c663fc79c9bb)
在grafana 上看一看到这个指标的存在的
![image](https://github.com/aide-family/moon/assets/48739305/17a4864b-c4d6-4979-bf6f-dbfc129360da)

### What did you expect to happen?

是我的配置有什么问题嘛，我需要做什么才能让它正常工作?

### How can we reproduce it (as minimally and precisely as possible)?

docker run -d --name moon-server -p 8001:8000 -p 8888:8888 -p 8000:80 -v ./moon/server/db:/app/db -v ./moon/server/cache:/app/cache -v ./moon/server/log:/app/log aidemoonio/moon-server:latest

docker run -d --name moon-agent -p 8002:8000 -v ./moon/agent/cache:/app/cache -v ./moon/agent/log:/app/log aidemoonio/moon-agent:latest

是通过docker 部署方式启动的

prometheus 是可以在部署moon主机中正常通信的

### moon version

latest和v0.0.26

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

**Comment by hanguanglinyun** [comment]
![image](https://github.com/aide-family/moon/assets/48739305/7d932141-8bf7-44d6-b3de-7bb7bcfae6c1)
是这个web的地址？

**Comment by aide-cloud** [comment]
目前没有实现类似内网这种的代理， 所以在moon web端查看数据， 需要一个全局环境都能访问的数据源地址，你这个问题提醒我了， 后面实现一下代理功能， 这样就能内网使用了， 给你点赞👍

**Comment by hanguanglinyun** [comment]
![image](https://github.com/aide-family/moon/assets/48739305/e4bf9c96-5098-427f-a9c6-354f2c2f07a3)
好的，我试一下，我以为是像grafana数据源的方式添加

**Comment by hanguanglinyun** [comment]
可以了，可以正常运行了，是单独部署moon-server就可以使用了嘛? moon-agent的功能是什么？

**Comment by aide-cloud** [comment]
server只是管理， 告警数据有agent来生成的， 所以如果你需要实际的告警， 需要agent去处理策略和生产事件
