### ISSUE TITLE
配置告警无响应

### ISSUE THREAD

**Issue by hanguanglinyun** [aide-family/moon#145]
### What happened?

告警策略配置
![image](https://github.com/aide-family/moon/assets/48739305/92da0579-1280-4f6d-8165-407bbc912866)

告警数据是存在的
![image](https://github.com/aide-family/moon/assets/48739305/548934e7-f447-4f55-9ffd-820463a4682e)

策略已启用
![image](https://github.com/aide-family/moon/assets/48739305/ee34f600-547e-44f0-b169-ce34eb728de4)

实时告警中没有告警信息
![image](https://github.com/aide-family/moon/assets/48739305/92d2427e-04b6-47e5-8591-befb03278733)

### What did you expect to happen?

如何让告警产生
![image](https://github.com/aide-family/moon/assets/48739305/970b1098-f157-4381-8dd9-ad9a937f6a0b)

### How can we reproduce it (as minimally and precisely as possible)?

docker部署

### Anything else we need to know?

moon-servser和moon-agent 是没有报错日志

### moon version

v0.0.26

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

**Comment by aide-cloud** [comment]
1. 确保策略状态开启
2. 策略组状态开启
3. 确保agent和server通信正常
4. 确保设置的持续时间和数据阈值一定有数据

如果以上不生效， 关闭策略组，等待10s后重新开启
