### ISSUE TITLE
docker-compose 一键部署后，验证码报错

### ISSUE THREAD

**Issue by qybf** [aide-family/moon#92]
![image](https://github.com/aide-family/moon/assets/47775316/a0af3857-4230-4291-b3e2-68e329a9ffa4)

前段容器日志如下：
![image](https://github.com/aide-family/moon/assets/47775316/9370e805-663d-4c53-9f54-3ca74f114ebe)

**Comment by qybf** [comment]
![image](https://github.com/aide-family/moon/assets/47775316/788a6b1d-55c4-4232-9781-760a9d5d5039)
进到容器里面，确实什么都没有

**Comment by aide-cloud** [comment]
这里可能是访问的地址和实际地址不符合导致，如果是在本机，用localhost:8000方式访问应该是没问题的，你是否是在虚拟机部署，然后访问的是虚拟机IP？ 如果是这样， 需要你只啊虚拟机配置Nginx代理，把前后端配置在同域下

**Comment by aide-cloud** [comment]
```conf
# api
location /api {
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_pass http://localhost:8001;
}
# web
location / {

		proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      		proxy_pass http://localhost:8000;
}
```

**Comment by qybf** [comment]
> ```
> # api
> location /api {
> 		proxy_set_header Host $host;
> 		proxy_set_header X-Real-IP $remote_addr;
> 		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> 		proxy_pass http://localhost:8001;
> }
> # web
> location / {
> 
> 		proxy_set_header Host $host;
>                 proxy_set_header X-Real-IP $remote_addr;
>                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>       		proxy_pass http://localhost:8000;
> }
> ```

是的，我是在虚拟机部署并且访问的虚拟机ip，那我试试配个代理

**Comment by qybf** [comment]
> ```
> # api
> location /api {
> 		proxy_set_header Host $host;
> 		proxy_set_header X-Real-IP $remote_addr;
> 		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
> 		proxy_pass http://localhost:8001;
> }
> # web
> location / {
> 
> 		proxy_set_header Host $host;
>                 proxy_set_header X-Real-IP $remote_addr;
>                 proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>       		proxy_pass http://localhost:8000;
> }
> ```

已解决，我再冒昧的问一下，初始管理员用户密码是啥，我看文档里面没有写

**Comment by aide-cloud** [comment]
123456
