### ISSUE TITLE
为什么我无法选择通知对象

### ISSUE THREAD

**Issue by qybf** [aide-family/moon#93]
我定义了两个机器人
![db21e264-6182-42e9-9c5d-99e4b0cc4d23](https://github.com/aide-family/moon/assets/47775316/90c1be0e-33cf-45b5-b84a-f9a24daefa57)
在策略列表里面点击通知对象，什么都不显示，点添加也没反应
![image](https://github.com/aide-family/moon/assets/47775316/fd1582d4-e4bc-4cbb-83c7-c40328aa4227)

**Comment by aide-cloud** [comment]
修复了，拉一下最新代码

**Comment by qybf** [comment]
> 修复了，拉一下最新代码 需要创建报警组，绑定部分是绑定的报警组

![image](https://github.com/aide-family/moon/assets/47775316/e601c61c-bcff-4695-89bc-e9f89d2b7240)
点击确定时又报错

**Comment by aide-cloud** [comment]
点添加， 再确定
